import type { Metadata } from "next";
import {
  Inter,
  Permanent_Marker,
  Sacramento,
  Montserrat,
  Anton,
  UnifrakturMaguntia,
  Satisfy,
  IM_Fell_DW_Pica,
  Rochester,
  Arimo,
} from "next/font/google";
import "./globals.css";
import { cn } from "@/lib/utils";

const inter = Inter({ subsets: ["latin"], variable: "--font-inter" });
const permanent_marker = Permanent_Marker({
  weight: "400",
  subsets: ["latin"],
  variable: "--font-permanent_marker",
});
const sacramento = Sacramento({
  weight: "400",
  subsets: ["latin"],
  variable: "--font-sacramento",
});

const montserrat = Montserrat({
  weight: "400",
  subsets: ["latin"],
  variable: "--font-montserrat",
});

const anton = Anton({
  weight: "400",
  subsets: ["latin"],
  variable: "--font-anton",
});

const unifrakturmaguntia = UnifrakturMaguntia({
  weight: "400",
  subsets: ["latin"],
  variable: "--font-unifrakturmaguntia",
});

const satisfy = Satisfy({
  weight: "400",
  subsets: ["latin"],
  variable: "--font-satisfy",
});

const im = IM_Fell_DW_Pica({
  weight: "400",
  subsets: ["latin"],
  variable: "--font-im",
});

const rochester = Rochester({
  weight: "400",
  subsets: ["latin"],
  variable: "--font-rochester",
});

const arimo = Arimo({
  weight: "400",
  subsets: ["latin"],
  variable: "--font-arimo",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body
        className={cn(
          inter.variable,
          permanent_marker.variable,
          sacramento.variable,
          montserrat.variable,
          anton.variable,
          unifrakturmaguntia.variable,
          satisfy.variable,
          im.variable,
          rochester.variable,
          arimo.variable,
          "font-sans"
        )}
      >
        {children}
      </body>
    </html>
  );
}
